"""Removed verse_id relationship

Revision ID: 1777e93bfdd4
Revises: dfd423398585
Create Date: 2024-04-29 17:03:42.181308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1777e93bfdd4'
down_revision: Union[str, None] = 'dfd423398585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('manas_translations_verse_id_fkey', 'manas_translations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('manas_translations_verse_id_fkey', 'manas_translations', 'manas_verses', ['verse_id'], ['id'])
    # ### end Alembic commands ###
