"""added verse_id foreign key

Revision ID: 26d9bf212cab
Revises: 1777e93bfdd4
Create Date: 2024-04-29 17:09:45.224980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d9bf212cab'
down_revision: Union[str, None] = '1777e93bfdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'manas_translations', 'manas_verses', ['verse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manas_translations', type_='foreignkey')
    # ### end Alembic commands ###
